In [2]:
import json
import nltk
import numpy as np
# from __future__ import unicode_literals
from hazm import *
import pandas as pd
from collections import OrderedDict
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
import collections
import re

In [3]:
file = open('out.jsonl', 'r')
s = file.readlines()


print('There is {} item available'.format(len(s)))

There is 1000 item available


##  Json example:
   

```
{
  "_id": "5b4f7280020eb20597f40200",
  "NewsAgency": "AsrIran",
  "newsCode": "621582",
  "newsLink": "http://www.asriran.com/fa/news/621582",
  "date": "تاریخ انتشار:  ۱۴:۴۷ - ۲۷ تير ۱۳۹۷ - 18 July 2018",
  "newsPath": "صفحه نخست » اقتصادی",
  "newsPathLinks": {
    "صفحه نخست": "/fa/archive?service_id=1",
    "اقتصادی": "/fa/archive?service_id=1&amp;cat_id=4"
  },
  "title": "تعداد شعب داخلی شبکه بانکي کاهش یافت",
  "rutitr": "",
  "subtitle": "تعداد کل شعب داخل کشور شبکه بانکي در پایان خرداد ماه 1397، به 20598 شعبه ‌رسيد.",
  "body": "تعداد کل شعب داخل کشور شبکه بانکي در پایان خرداد ماه 1397 نسبت به پايان اسفند ماه&nbsp; 1396، 0.6 درصد کاهش یافت.به گزارش عصرایران به نقل از بانک مرکزی، تعداد کل شعب داخل کشور شبکه بانکي در پایان خرداد ماه 1397، به&nbsp; 20598&nbsp; شعبه &zwnj;رسيد.بر این اساس و در پایان خرداد ماه 1397، تعداد شعب بانک هاي دولتي 8681 شعبه ( 42.1 درصد) ، بانک هاي خصوصي شده 6461 شعبه ( 31.4 درصد) و بانک هاي خصوصي و موسسات اعتباري 5456 شعبه ( 26.5 درصد) است.همچنین تعداد کل شعب ريالي ـ ارزي شبکه بانکي کشور بالغ بر 3787 شعبه، تعداد شعب شهري 19735 و شعب روستايي 863 شعبه است.بر اساس این گزارش تعداد شعب خارج از کشور شبکه بانکي تعداد 48 شعبه و تعداد باجه هاي بانکي کشور در پايان خرداد ماه 1397 تعداد 2274&nbsp; باجه است و213 شعبه بانکی نیز در مناطق آزاد تجاري قرار دارند.بررسی تعداد شعب داخل کشور بانک ها و موسسات اعتباری&nbsp; به تفکیک استانی در پایان خرداد ماه سال 1397 نیز نشان می دهد که استان&zwnj;هاي تهران، اصفــهان و خراسان رضوي به &zwnj;ترتيب با 4049، 1431 و 1318 شعبه داراي بيشترين تعداد شعب هستند.گزارش فصلی &laquo;اطلاعات تعداد شعب بانک ها&nbsp; و موسسات اعتباری&raquo; توسط اداره اطلاعات بانکی بانک مرکزی تهیه و در آن تعداد شعب&nbsp; بانک ها و موسسات اعتباری به تفکیک گروه های بانکی و استانی اعلام می شود.",
  "bodyHtml": " <div align=\"justify\"><img class=\"image_btn\" style=\"margin: 0px 14px;\" title=\"تعداد شعب داخلی شبکه بانکي کاهش یافت\" src=\"http://cdn.asriran.com/files/fa/news/1397/4/27/875553_322.jpg\" alt=\"تعداد شعب داخلی شبکه بانکي کاهش یافت\" width=\"250\" height=\"169\" align=\"left\"/>تعداد کل شعب داخل کشور شبکه بانکي در پایان خرداد ماه 1397 نسبت به پايان اسفند ماه&nbsp; 1396، 0.6 درصد کاهش یافت.<br/><br/>به گزارش <span style=\"color: #0000cd;\">عصرایران</span> به نقل از بانک مرکزی، تعداد کل شعب داخل کشور شبکه بانکي در پایان خرداد ماه 1397، به&nbsp; 20598&nbsp; شعبه &zwnj;رسيد.<br/><br/>بر این اساس و در پایان خرداد ماه 1397، تعداد شعب بانک هاي دولتي 8681 شعبه ( 42.1 درصد) ، بانک هاي خصوصي شده 6461 شعبه ( 31.4 درصد) و بانک هاي خصوصي و موسسات اعتباري 5456 شعبه ( 26.5 درصد) است.<br/><br/>همچنین تعداد کل شعب ريالي ـ ارزي شبکه بانکي کشور بالغ بر 3787 شعبه، تعداد شعب شهري 19735 و شعب روستايي 863 شعبه است.<br/><br/><img class=\"image_btn\" style=\"margin: 0px auto; display: block;\" title=\"تعداد شعب داخلی شبکه بانکي کاهش یافت\" src=\"http://cdn.asriran.com/files/fa/news/1397/4/27/875556_701.jpg\" alt=\"تعداد شعب داخلی شبکه بانکي کاهش یافت\" width=\"404\" height=\"300\" align=\"\"/><br/><br/>بر اساس این گزارش تعداد شعب خارج از کشور شبکه بانکي تعداد 48 شعبه و تعداد باجه هاي بانکي کشور در پايان خرداد ماه 1397 تعداد 2274&nbsp; باجه است و213 شعبه بانکی نیز در مناطق آزاد تجاري قرار دارند.<br/><br/>بررسی تعداد شعب داخل کشور بانک ها و موسسات اعتباری&nbsp; به تفکیک استانی در پایان خرداد ماه سال 1397 نیز نشان می دهد که استان&zwnj;هاي تهران، اصفــهان و خراسان رضوي به &zwnj;ترتيب با 4049، 1431 و 1318 شعبه داراي بيشترين تعداد شعب هستند.<br/><br/>گزارش فصلی &laquo;اطلاعات تعداد شعب بانک ها&nbsp; و موسسات اعتباری&raquo; توسط اداره اطلاعات بانکی بانک مرکزی تهیه و در آن تعداد شعب&nbsp; بانک ها و موسسات اعتباری به تفکیک گروه های بانکی و استانی اعلام می شود.</div> <div class=\"wrapper\"/> ",
  "tags": {
    "بانک مرکزی": "/fa/tag/1/بانک مرکزی",
    "شعب داخلی": "/fa/tag/1/شعب داخلی"
  }
}

```



## Load jsons into Dataframe

In [4]:
def prepare_json(j):
#     clear newsPath
    newsPath = j['newsPath']
    newsPath = newsPath.replace('عصرايران دو » ','')
    newsPath = newsPath.replace('صفحه نخست » ','')
    j['newsPath'] = newsPath

    
    
    return j
    
        
raw_data = []
for item in s:
    try:
        j = json.loads(item)

        prepare_json(j)
#         print(list(j['tags'].keys())[0])
        raw_data.append({'title': j['title'], 'body':j['body'], 'newsAgency': j['NewsAgency'],
                         'newsPath':j['newsPath'], 'tag':list(j['tags'].keys())[0] })
    except:
        pass
df = pd.DataFrame(raw_data)
df.head()

body newsAgency   newsPath  \
0  مدیرعامل سابق استقلال از عضویت در هیات مدیره ا...    AsrIran      ورزشی   
1  دادستان انتظامی مالیاتی سازمان امور مالیاتی گف...    AsrIran    اجتماعی   
2  قیمت سبد نفتی اوپک دیروز به روند کاهشی خود ادا...    AsrIran    اقتصادی   
3  رئیس فراکسیون فرهنگیان مجلس خطاب به وزیر آموزش...    AsrIran    اجتماعی   
4  رئیس صندوق بین&zwnj;المللی پول در آستانه نشست ...    AsrIran  بین الملل   

                    tag                                              title  
0               استقلال   افتخاری قید ماندن در هیات مدیره استقلال را هم زد  
1                مالیات  دادستان انتظامی مالیاتی سازمان مالیات: آخرین ا...  
2                  اوپک  قیمت سبد نفتی اوپک یک گام دیگر عقب نشست/ 70 دل...  
3         آموزش و پرورش  حاجی‌بابایی به بطحایی:آقای وزیر در اطلاع‌رسانی...  
4  صندوق بین المللی پول  رئیس صندوق بین‌المللی پول: آمریکا از جنگ تعرفه...

# Encoding categorical features 

In [9]:
categories = ['newsAgency','newsPath']

le = LabelEncoder()
df[categories] = df[categories].apply(le.fit_transform)




X = df[['title','body','newsAgency','tag']]
y = df['newsPath']

X.head()
# y.head()

title  \
0   افتخاری قید ماندن در هیات مدیره استقلال را هم زد   
1  دادستان انتظامی مالیاتی سازمان مالیات: آخرین ا...   
2  قیمت سبد نفتی اوپک یک گام دیگر عقب نشست/ 70 دل...   
3  حاجی‌بابایی به بطحایی:آقای وزیر در اطلاع‌رسانی...   
4  رئیس صندوق بین‌المللی پول: آمریکا از جنگ تعرفه...   

                                                body  newsAgency  \
0  مدیرعامل سابق استقلال از عضویت در هیات مدیره ا...           0   
1  دادستان انتظامی مالیاتی سازمان امور مالیاتی گف...           0   
2  قیمت سبد نفتی اوپک دیروز به روند کاهشی خود ادا...           0   
3  رئیس فراکسیون فرهنگیان مجلس خطاب به وزیر آموزش...           0   
4  رئیس صندوق بین&zwnj;المللی پول در آستانه نشست ...           0   

                    tag  
0               استقلال  
1                مالیات  
2                  اوپک  
3         آموزش و پرورش  
4  صندوق بین المللی پول

# split Trainset and Testset

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

print('Train size: ',len(X_train))
print('Test size : ',len(X_test))

Train size:  698
Test size :  300


In [11]:
def calculate_classes_probebility(words_class_dict, N_document):
    '''
    P(Ci) = (number of document in class 'i') / N_document
    
    @param words_class_dict : dictionary which keys are classes and values are number of words in that class
    @param N_document : number of all words 
    
    @return : dictionary which keys are classes and values are probebility of each class
    
    
    example: calculate_classes_probebility({'0':10,'1':20,'2':15}, 45)
    '''
    
    
    probs = {}
    
    for class_name, doc_num in words_class_dict.items():
        probs[class_name] = doc_num/N_document
        
    return probs


def calculate_likelihood_of_word(word_class_dict, class_doc_count_dict):
    '''
    P(Wi|Cj) = (number of Wi in class 'j') / (total number of words in class 'Cj')
    
    @param word_class_dict : dictionary which keys are classes and values are number of words in that class
    @param class_doc_count_dict : number of all words 
    
    @return : dictionary which keys are words and values are probebility of each class
    
    
    
    '''

In [12]:
calculate_classes_probebility({'0':10,'1':20,'2':15},45)

{'0': 0.2222222222222222, '1': 0.4444444444444444, '2': 0.3333333333333333}

In [15]:
def preprocess(data):
    normalizer = Normalizer()
    stemmer = Stemmer()
    lemmatizer = Lemmatizer()
    
    final_tokens = []

    for item in data:
        for sent in sent_tokenize(item):
            sent = normalizer.normalize(sent)
            tokens = word_tokenize(sent) 
#             stems = []
#             lemas = []
#             print(tokens)

            for t in tokens:
                final_tokens.append(stemmer.stem(t))
#                 lemas.append(lemmatizer.lemmatize(stems))
#             print(stems)
#             print('-------------------------------------------------------')
    return final_tokens

In [33]:


vectorizer = CountVectorizer()
data_corpus = X['title'].values
# test_corpus = X_test['title'].values


# labeled_features = dict(zip(data_corpus , y_train.values))


# data_corpus = preprocess(data_corpus)

words = vectorizer.fit_transform(data_corpus) 
# test_words = vectorizer.fit_transform(test_corpus)

print(words.toarray())
print('*******')
# print(test_words.toarray())
# labeled_features.items
# print(vectorizer.get_feature_names())
# print(all_words_in_title)
# sum(words.toarray()[4])
words[699:].shape


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
*******


(299, 3423)

In [42]:
classifier = MultinomialNB()

classifier.fit(words[0:698].toarray(),y_train.values)



MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [39]:
predict = classifier.predict(words[699:].toarray())
sum(predict == y_test)

50


# TFIDF 

In [223]:
data_corpus = X_train['title'].values
# data_corpus = [re.sub('([0-9])+','00number00',data) for data in data_corpus]

tfidf = TfidfVectorizer(min_df=2, max_df=0.5,ngram_range=(1,0))
features = tfidf.fit_transform(data_corpus)

tfidf_values = pd.DataFrame(features.todense(),columns=tfidf.get_feature_names())


test_corpus = X_test['title'].values
# data_corpus = [re.sub('([0-9])+','00number00',data) for data in data_corpus]

test_tfidf = TfidfVectorizer(min_df=2, max_df=0.5,ngram_range=(1,0))
test_features = test_tfidf.fit_transform(test_corpus)

test_tfidf_values = pd.DataFrame(test_features.todense(), columns=test_tfidf.get_feature_names())


In [228]:
tfidf_values.shape

(698, 1076)

In [225]:
classifier = MultinomialNB()

classifier.fit(tfidf_values ,y_train.values)



MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [229]:
classifier.predict(tfidf_values)

ValueError: could not convert string to float: 'قاچاق بنزین رونق گرفت/ خرید و فروش کارت سوخت با قیمت 30 تا 50 هزار تومان!'